load("//engine/build:isaac.bzl", "isaac_cc_module", "isaac_component")

isaac_cc_module(
    name = "components",
    deps = [
        ":manual_control",
    ]
)

isaac_component(
    name = "manual_control",
    deps = [
    
    ],
)
